from __future__ import annotations

# Query lexicons are intentionally limited to bounded classes: helper words,
# intent modifiers and geo aliases. Topic words are never listed here; they are
# what remains after these bounded classes are removed from the query.

QUERY_HELPER_TERMS = frozenset(
    {
        "a",
        "an",
        "and",
        "are",
        "best",
        "for",
        "from",
        "how",
        "in",
        "near",
        "of",
        "on",
        "or",
        "the",
        "to",
        "vs",
        "what",
        "when",
        "where",
        "which",
        "who",
        "why",
        "без",
        "близко",
        "бывает",
        "быстро",
        "в",
        "во",
        "возле",
        "все",
        "выбрать",
        "где",
        "для",
        "до",
        "зачем",
        "и",
        "из",
        "или",
        "как",
        "кака",
        "какая",
        "каки",
        "какие",
        "какой",
        "когда",
        "котор",
        "кто",
        "куда",
        "лучше",
        "лучшие",
        "лучший",
        "на",
        "над",
        "недалеко",
        "о",
        "об",
        "около",
        "от",
        "перед",
        "по",
        "под",
        "после",
        "почем",
        "почему",
        "при",
        "про",
        "ряд",
        "рядом",
        "с",
        "сам",
        "самая",
        "самые",
        "самый",
        "тако",
        "такое",
        "топ",
        "у",
        "чем",
        "через",
        "что",
    }
)

COMMERCIAL_INTENT_TERMS = frozenset(
    {
        "arenda",
        "book",
        "buy",
        "cost",
        "delivery",
        "discount",
        "install",
        "installation",
        "order",
        "price",
        "pricing",
        "quote",
        "repair",
        "sale",
        "service",
        "services",
        "shop",
        "аренд",
        "аренда",
        "аренду",
        "бронирова",
        "бронь",
        "вызов",
        "доставк",
        "доставка",
        "заказ",
        "заказать",
        "заказыва",
        "записа",
        "записаться",
        "запис",
        "куп",
        "купит",
        "купить",
        "купл",
        "магазин",
        "монтаж",
        "недорог",
        "онлайн",
        "оплат",
        "оплата",
        "покупк",
        "прайс",
        "продаж",
        "ремонт",
        "скидк",
        "стоимост",
        "стоимость",
        "тариф",
        "услуг",
        "услуга",
        "услуги",
        "цен",
        "цена",
        "цены",
        "цену",
    }
)

INFORMATIONAL_INTENT_TERMS = frozenset(
    {
        "comparison",
        "example",
        "examples",
        "faq",
        "guide",
        "instruction",
        "instructions",
        "review",
        "reviews",
        "tutorial",
        "виды",
        "гайд",
        "инструкц",
        "инструкция",
        "инструкции",
        "обзор",
        "обзоры",
        "описание",
        "отзывы",
        "пример",
        "примеры",
        "рейтинг",
        "сравнение",
        "советы",
    }
)

NAVIGATIONAL_INTENT_TERMS = frozenset(
    {
        "account",
        "cabinet",
        "contacts",
        "login",
        "official",
        "site",
        "website",
        "вход",
        "кабинет",
        "контакт",
        "контакты",
        "личн",
        "официальн",
        "официальный",
        "сайт",
    }
)

LOCAL_INTENT_TERMS = frozenset(
    {
        "address",
        "city",
        "local",
        "map",
        "near",
        "nearby",
        "адрес",
        "город",
        "карт",
        "поблизост",
        "район",
        "ряд",
        "рядом",
    }
)

QUERY_INTENT_MODIFIER_TERMS = frozenset(
    set(COMMERCIAL_INTENT_TERMS)
    | set(INFORMATIONAL_INTENT_TERMS)
    | set(NAVIGATIONAL_INTENT_TERMS)
    | set(LOCAL_INTENT_TERMS)
)

RUSSIAN_CITY_ALIASES_100K = {
    "москва": ("москва", "москв", "мск", "moscow"),
    "санкт-петербург": ("санкт", "петербург", "петербург", "спб", "питер", "ленинград", "saint", "petersburg"),
    "новосибирск": ("новосибирск", "нск", "novosibirsk"),
    "екатеринбург": ("екатеринбург", "екб", "ekaterinburg", "yekaterinburg"),
    "казань": ("казань", "казан", "kazan"),
    "нижний новгород": ("нижн", "новгород", "нн", "nizhny", "novgorod"),
    "челябинск": ("челябинск", "челяб", "chelyabinsk"),
    "красноярск": ("красноярск", "krasnoyarsk"),
    "самара": ("самара", "самар", "samara"),
    "уфа": ("уфа", "ufa"),
    "ростов-на-дону": ("ростов", "дон", "дону", "rostov"),
    "омск": ("омск", "omsk"),
    "краснодар": ("краснодар", "krasnodar"),
    "воронеж": ("воронеж", "voronezh"),
    "пермь": ("пермь", "перм", "perm"),
    "волгоград": ("волгоград", "volgograd"),
    "саратов": ("саратов", "saratov"),
    "тюмень": ("тюмень", "тюмен", "tyumen"),
    "тольятти": ("тольятти", "tolyatti"),
    "ижевск": ("ижевск", "izhevsk"),
    "барнаул": ("барнаул", "barnaul"),
    "ульяновск": ("ульяновск", "ulyanovsk"),
    "иркутск": ("иркутск", "irkutsk"),
    "хабаровск": ("хабаровск", "khabarovsk"),
    "ярославль": ("ярославль", "ярославл", "yaroslavl"),
    "владивосток": ("владивосток", "vladivostok"),
    "махачкала": ("махачкала", "makhachkala"),
    "томск": ("томск", "tomsk"),
    "оренбург": ("оренбург", "orenburg"),
    "кемерово": ("кемерово", "kemerovo"),
    "новокузнецк": ("новокузнецк", "novokuznetsk"),
    "рязань": ("рязань", "рязан", "ryazan"),
    "набережные челны": ("набережн", "челн", "naberezhnye", "chelny"),
    "астрахань": ("астрахань", "астрахан", "astrakhan"),
    "пенза": ("пенза", "penza"),
    "киров": ("киров", "kirov"),
    "липецк": ("липецк", "lipetsk"),
    "чебоксары": ("чебоксар", "чебоксары", "cheboksary"),
    "балашиха": ("балашиха", "balashikha"),
    "калининград": ("калининград", "kaliningrad"),
    "тула": ("тула", "tula"),
    "курск": ("курск", "kursk"),
    "севастополь": ("севастополь", "севастопол", "sevastopol"),
    "сочи": ("сочи", "sochi"),
    "ставрополь": ("ставрополь", "ставропол", "stavropol"),
    "улан-удэ": ("улан", "удэ", "ude"),
    "тверь": ("тверь", "твер", "tver"),
    "магнитогорск": ("магнитогорск", "magnitogorsk"),
    "иваново": ("иваново", "ivanovo"),
    "брянск": ("брянск", "bryansk"),
    "белгород": ("белгород", "belgorod"),
    "сургут": ("сургут", "surgut"),
    "владимир": ("владимир", "vladimir"),
    "нижний тагил": ("нижн", "тагил", "tagil"),
    "чита": ("чита", "chita"),
    "архангельск": ("архангельск", "arkhangelsk"),
    "симферополь": ("симферополь", "симферопол", "simferopol"),
    "калуга": ("калуга", "kaluga"),
    "смоленск": ("смоленск", "smolensk"),
    "волжский": ("волжск", "volzhsky"),
    "якутск": ("якутск", "yakutsk"),
    "саранск": ("саранск", "saransk"),
    "череповец": ("череповец", "cherepovets"),
    "курган": ("курган", "kurgan"),
    "вологда": ("вологда", "vologda"),
    "орел": ("орел", "орёл", "orel"),
    "владикавказ": ("владикавказ", "vladikavkaz"),
    "подольск": ("подольск", "podolsk"),
    "грозный": ("грозн", "грозный", "grozny"),
    "мурманск": ("мурманск", "murmansk"),
    "тамбов": ("тамбов", "tambov"),
    "петрозаводск": ("петрозаводск", "petrozavodsk"),
    "стерлитамак": ("стерлитамак", "sterlitamak"),
    "нижневартовск": ("нижневартовск", "nizhnevartovsk"),
    "кострома": ("кострома", "kostroma"),
    "новороссийск": ("новороссийск", "novorossiysk"),
    "йошкар-ола": ("йошкар", "ола", "yoshkar"),
    "химки": ("химки", "khimki"),
    "таганрог": ("таганрог", "taganrog"),
    "комсомольск-на-амуре": ("комсомольск", "амур", "amur"),
    "сыктывкар": ("сыктывкар", "syktyvkar"),
    "нальчик": ("нальчик", "nalchik"),
    "нижнекамск": ("нижнекамск", "nizhnekamsk"),
    "шахты": ("шахты", "shakhty"),
    "дзержинск": ("дзержинск", "dzerzhinsk"),
    "орск": ("орск", "orsk"),
    "братск": ("братск", "bratsk"),
    "ангарск": ("ангарск", "angarsk"),
    "благовещенск": ("благовещенск", "blagoveshchensk"),
    "энгельс": ("энгельс", "engels"),
    "старый оскол": ("стар", "оскол", "oskol"),
    "великий новгород": ("велик", "новгород", "novgorod"),
    "королев": ("королев", "королёв", "korolev"),
    "псков": ("псков", "pskov"),
    "мытищи": ("мытищ", "мытищи", "mytishchi"),
    "люберцы": ("люберц", "люберцы", "lyubertsy"),
    "бийск": ("бийск", "biysk"),
    "прокопьевск": ("прокопьевск", "prokopyevsk"),
    "южно-сахалинск": ("южн", "сахалинск", "sakhalinsk"),
    "балаково": ("балаково", "balakovo"),
    "рыбинск": ("рыбинск", "rybinsk"),
    "армавир": ("армавир", "armavir"),
    "абакан": ("абакан", "abakan"),
    "северодвинск": ("северодвинск", "severodvinsk"),
    "петропавловск-камчатский": ("петропавловск", "камчатск", "kamchatsky"),
    "норильск": ("норильск", "norilsk"),
    "уссурийск": ("уссурийск", "ussuriysk"),
    "волгодонск": ("волгодонск", "volgodonsk"),
    "сызрань": ("сызрань", "сызран", "syzran"),
    "новочеркасск": ("новочеркасск", "novocherkassk"),
    "каменск-уральский": ("каменск", "уральск", "uralsky"),
    "златоуст": ("златоуст", "zlatoust"),
    "электросталь": ("электросталь", "elektrostal"),
    "альметьевск": ("альметьевск", "almetyevsk"),
    "салават": ("салават", "salavat"),
    "миасс": ("миасс", "miass"),
    "копейск": ("копейск", "kopeysk"),
    "пятигорск": ("пятигорск", "pyatigorsk"),
    "хасавюрт": ("хасавюрт", "khasavyurt"),
    "находка": ("находка", "nakhodka"),
    "рубцовск": ("рубцовск", "rubtsovsk"),
    "березники": ("березники", "berezniki"),
    "коломна": ("коломна", "kolomna"),
    "майкоп": ("майкоп", "maykop"),
    "одинцово": ("одинцово", "odintsovo"),
    "кисловодск": ("кисловодск", "kislovodsk"),
    "серпухов": ("серпухов", "serpukhov"),
    "ковров": ("ковров", "kovrov"),
    "невинномысск": ("невинномысск", "nevinnomyssk"),
    "домодедово": ("домодедово", "domodedovo"),
    "нефтекамск": ("нефтекамск", "neftekamsk"),
    "черкесск": ("черкесск", "cherkessk"),
    "димитровград": ("димитровград", "dimitrovgrad"),
    "новочебоксарск": ("новочебоксарск", "novocheboksarsk"),
    "каспийск": ("каспийск", "kaspiysk"),
    "обнинск": ("обнинск", "obninsk"),
    "назрань": ("назрань", "назран", "nazran"),
    "кызыл": ("кызыл", "kyzyl"),
    "элиста": ("элиста", "elista"),
    "батайск": ("батайск", "bataysk"),
    "новый уренгой": ("нов", "уренгой", "urengoy"),
    "октябрьский": ("октябрьск", "oktyabrsky"),
    "долгопрудный": ("долгопрудн", "dolgoprudny"),
    "реутов": ("реутов", "reutov"),
    "жуковский": ("жуковск", "zhukovsky"),
    "пушкино": ("пушкино", "pushkino"),
    "артем": ("артем", "артём", "artyom"),
    "евпатория": ("евпатория", "yevpatoria"),
    "муром": ("муром", "murom"),
    "новомосковск": ("новомосковск", "novomoskovsk"),
    "северск": ("северск", "seversk"),
    "есентуки": ("ессентуки", "есентуки", "yessentuki"),
    "ноябрьск": ("ноябрьск", "noyabrsk"),
    "ачинск": ("ачинск", "achinsk"),
    "бердск": ("бердск", "berdsk"),
    "елец": ("елец", "yelets"),
    "арзамас": ("арзамас", "arzamas"),
    "обь": ("обь", "ob"),
}

QUERY_GEO_MODIFIER_TERMS = frozenset(
    set(LOCAL_INTENT_TERMS)
    | {alias for aliases in RUSSIAN_CITY_ALIASES_100K.values() for alias in aliases}
)


def _alias_group_map(groups: dict[str, tuple[str, ...]]) -> dict[str, frozenset[str]]:
    alias_map: dict[str, frozenset[str]] = {}
    for aliases in groups.values():
        expanded = frozenset(aliases)
        for alias in aliases:
            alias_map[alias] = expanded
    return alias_map


GEO_TOKEN_ALIASES = _alias_group_map(RUSSIAN_CITY_ALIASES_100K)
INTENT_TOKEN_ALIASES = _alias_group_map(
    {
        "price": ("цен", "цена", "цены", "цену", "стоимост", "стоимость", "прайс", "price", "cost", "pricing"),
        "buy": ("куп", "купит", "купить", "купл", "покупк", "buy", "shop"),
        "order": ("заказ", "заказать", "заказыва", "order", "book"),
        "rent": ("аренд", "аренда", "аренду", "rent", "arenda"),
        "review": ("отзывы", "обзор", "рейтинг", "review", "reviews"),
        "repair": ("ремонт", "repair"),
    }
)

QUERY_NON_CORE_MODIFIER_TERMS = frozenset(
    set(QUERY_HELPER_TERMS) | set(QUERY_INTENT_MODIFIER_TERMS) | set(QUERY_GEO_MODIFIER_TERMS)
)

COMMERCIAL_INTENT_KEYWORDS = COMMERCIAL_INTENT_TERMS
LOCAL_INTENT_KEYWORDS = frozenset(set(LOCAL_INTENT_TERMS) | set(QUERY_GEO_MODIFIER_TERMS))
INFORMATIONAL_INTENT_KEYWORDS = frozenset(set(QUERY_HELPER_TERMS) | set(INFORMATIONAL_INTENT_TERMS))
NAVIGATIONAL_INTENT_KEYWORDS = NAVIGATIONAL_INTENT_TERMS
